### PR TITLE
Add other administrations since shutdowns first occured

### PR DESCRIPTION
**Pull request by aguynamedjoetoo**
Availability is all about comparing against previous metrics right? :P 

Figured it'd be fun to look at what other availabilities were since the first shutdown per administration.

Could absolutely be simplified, but brute force something something?

### CODE REVIEW

**Comment by thecaddy** [comment]
👍

**Comment by aguynamedjoetoo** [comment]
Whoops, just realized what the function itself does that I wasn't expecting, fix incoming in a bit!

**Comment by davekeane** [comment]
I have rewritten the math in [davekeane/gov-availability](https://github.com/davekeane/gov-availability) if you'd like to pull from there instead?

**Comment by aguynamedjoetoo** [comment]
@davekeane you da best! Was having some headaches thinking through it haha merging yours into mine now!

**Comment by aguynamedjoetoo** [comment]
@cmgiven should be good now! Just tested locally :D

**Comment by cmgiven** [comment]
Nice work! Fascinating how close the Carter and Reagan numbers end up being.

I'm going to close without merge as I think the additional numbers are too much for this simple project. But I'd absolutely encourage you to run with the data and do something comparative.

(Small note: Bush 41's end date is wrong.)

screen shot 2019-01-12 at 11 35 49 am

**Pull request closed without merging**
