### PR TITLE
We have a government again

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by cmgiven** [comment]
Heh, thanks for doing this, Alex. Sorry I missed this PR.

(redundant of dad9167)

**Comment by alex** [comment]
No worries, thanks for putting this together. Hopefully we won't need to use it again.

**Comment by cmgiven** [comment]
With any luck, we'll just get to wait until 2030 when we get our three nines back.

**Comment by alex** [comment]
Is that really what the math works out to? That's sobering.

**Comment by cmgiven** [comment]
Back of the napkin, but yeah, thereabouts. I think there's a metaphor in there.

**Pull request closed without merging**
